// actions/types.js
export const GET_TOURS_REQUEST = "GET_TOURS_REQUEST";
export const GET_TOURS_SUCCESS = "GET_TOURS_SUCCESS";
export const GET_TOURS_FAILURE = "GET_TOURS_FAILURE";

export const BOOKING_TOUR_REQUEST = "BOOKING_TOUR_REQUEST";
export const BOOKING_TOUR_SUCCESS = "BOOKING_TOUR_SUCCESS";
export const BOOKING_TOUR_FAILURE = "BOOKING_TOUR_FAILURE";

export const FIND_TOUR_REQUEST = "FIND_TOUR_REQUEST";
export const FIND_TOUR_SUCCESS = "FIND_TOUR_SUCCESS";
export const FIND_TOUR_FAILURE = "FIND_TOUR_FAILURE";


export const GET_TOUR_DETAILS_REQUEST = "GET_TOUR_DETAILS_REQUEST";
export const GET_TOUR_DETAILS_SUCCESS = "GET_TOUR_DETAILS_SUCCESS";
export const GET_TOUR_DETAILS_FAILURE = "GET_TOUR_DETAILS_FAILURE";

export const CANCEL_TOUR_REQUEST = "CANCEL_TOUR_REQUEST";
export const CANCEL_TOUR_SUCCESS = "CANCEL_TOUR_SUCCESS";
export const CANCEL_TOUR_FAILURE = "CANCEL_TOUR_FAILURE";


export const GET_TOUR_HISTORY_REQUEST = "GET_TOUR_HISTORY_REQUEST";
export const GET_TOUR_HISTORY_SUCCESS = "GET_TOUR_HISTORY_SUCCESS";
export const GET_TOUR_HISTORY_FAILURE = "GET_TOUR_HISTORY_FAILURE";


export const FILTER_TOURS_REQUEST = "FILTER_TOURS_REQUEST";
export const FILTER_TOURS_SUCCESS = "FILTER_TOURS_SUCCESS";
export const FILTER_TOURS_FAILURE = "FILTER_TOURS_FAILURE";

export const ADD_TO_FAVORITES_REQUEST = "ADD_TO_FAVORITES_REQUEST";
export const ADD_TO_FAVORITES_SUCCESS = "ADD_TO_FAVORITES_SUCCESS";
export const ADD_TO_FAVORITES_FAILURE = "ADD_TO_FAVORITES_FAILURE";


export const REMOVE_FROM_FAVORITES_REQUEST = "REMOVE_FROM_FAVORITES_REQUEST";
export const REMOVE_FROM_FAVORITES_SUCCESS = "REMOVE_FROM_FAVORITES_SUCCESS";
export const REMOVE_FROM_FAVORITES_FAILURE = "REMOVE_FROM_FAVORITES_FAILURE";

export const POST_TOUR_REVIEW_REQUEST = "POST_TOUR_REVIEW_REQUEST";
export const POST_TOUR_REVIEW_SUCCESS = "POST_TOUR_REVIEW_SUCCESS";
export const POST_TOUR_REVIEW_FAILURE = "POST_TOUR_REVIEW_FAILURE";

export const CONTACT_TOUR_GUIDE_REQUEST = "CONTACT_TOUR_GUIDE_REQUEST";
export const CONTACT_TOUR_GUIDE_SUCCESS = "CONTACT_TOUR_GUIDE_SUCCESS";
export const CONTACT_TOUR_GUIDE_FAILURE = "CONTACT_TOUR_GUIDE_FAILURE";

export const LOAD_FAVORITES_REQUEST = "LOAD_FAVORITES_REQUEST";
export const LOAD_FAVORITES_SUCCESS = "LOAD_FAVORITES_SUCCESS";
export const LOAD_FAVORITES_FAILURE = "LOAD_FAVORITES_FAILURE";
