// WebSocket Actions
export const ADD_NEW_MESSAGE = "ADD_NEW_MESSAGE";
export const SET_CURRENT_SESSION_ID = "SET_CURRENT_SESSION_ID"
export const LOAD_MESSAGES_FOR_SESSION = "LOAD_MESSAGES_FOR_SESSION"
export const MESSAGE_CREATE_REQUEST = "MESSAGE_CREATE_REQUEST";
export const MESSAGE_CREATE_SUCCESS = "MESSAGE_CREATE_SUCCESS";
export const MESSAGE_CREATE_FAILURE = "MESSAGE_CREATE_FAILURE";


export const SESSION_CREATE_REQUEST = "SESSION_CREATE_REQUEST";
export const SESSION_CREATE_SUCCESS = "SESSION_CREATE_SUCCESS";
export const SESSION_CREATE_FAILURE = "SESSION_CREATE_FAILURE";
