export const GET_ALL_TOURS_REQUEST = "GET_ALL_TOURS_REQUEST";
export const GET_ALL_TOURS_SUCCESS = "GET_ALL_TOURS_SUCCESS";
export const GET_ALL_TOURS_FAILURE = "GET_ALL_TOURS_FAILURE";

export const GET_ALL_BOOKINGS_REQUEST = "GET_ALL_BOOKINGS_REQUEST";
export const GET_ALL_BOOKINGS_SUCCESS = "GET_ALL_BOOKINGS_SUCCESS";
export const GET_ALL_BOOKINGS_FAILURE = "GET_ALL_BOOKINGS_FAILURE";

export const GET_ALL_ACCOUNT_REQUEST = "GET_ALL_ACCOUNT_REQUEST";
export const GET_ALL_ACCOUNT_SUCCESS = "GET_ALL_ACCOUNT_SUCCESS";
export const GET_ALL_ACCOUNT_FAILURE = "GET_ALL_ACCOUNT_FAILURE";
