# --- build stage ---
FROM maven:3.9-eclipse-temurin-23 AS build
WORKDIR /src
COPY pom.xml .
COPY .mvn .mvn
COPY mvnw mvnw
RUN chmod +x mvnw
RUN ./mvnw -q -DskipTests dependency:go-offline
COPY src ./src
RUN ./mvnw -q clean package -DskipTests

# --- runtime stage ---
FROM eclipse-temurin:23-jre
WORKDIR /app
COPY --from=build /src/target/*-SNAPSHOT.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]
