// actions/types.js
export const FETCH_TOURS_REQUEST = "FETCH_TOURS_REQUEST";
export const FETCH_TOURS_SUCCESS = "FETCH_TOURS_SUCCESS";
export const FETCH_TOURS_FAILURE = "FETCH_TOURS_FAILURE";

export const ADD_TOUR_REQUEST = "ADD_TOUR_REQUEST";
export const ADD_TOUR_SUCCESS = "ADD_TOUR_SUCCESS";
export const ADD_TOUR_FAILURE = "ADD_TOUR_FAILURE";

export const EDIT_TOUR_REQUEST = "EDIT_TOUR_REQUEST";
export const EDIT_TOUR_SUCCESS = "EDIT_TOUR_SUCCESS";
export const EDIT_TOUR_FAILURE = "EDIT_TOUR_FAILURE";

export const DELETE_TOUR_REQUEST = "DELETE_TOUR_REQUEST";
export const DELETE_TOUR_SUCCESS = "DELETE_TOUR_SUCCESS";
export const DELETE_TOUR_FAILURE = "DELETE_TOUR_FAILURE";

export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAILURE = "GET_ALL_ORDERS_FAILURE";
