name: Build, Push to ECR & Restart EC2

on:
  push:
    branches: [main]
    paths:
      - "backend/tour-booking/**"
      - ".github/workflows/ecr-push.yml"

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: tourbooking-be

concurrency:
  group: deploy-be
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: backend/tour-booking
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          IMAGE_LATEST: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
          IMAGE_SHA: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
        run: |
          docker build --pull -t "$IMAGE_LATEST" .
          docker tag "$IMAGE_LATEST" "$IMAGE_SHA"

      - name: Push images to ECR
        env:
          IMAGE_LATEST: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
          IMAGE_SHA: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
        run: |
          docker push "$IMAGE_SHA"
          docker push "$IMAGE_LATEST"

  restart-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Restart be service via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          command_timeout: 2m
          script: |
            set -euxo pipefail

            # (Tuỳ chọn) login ECR để chắc ăn
            aws ecr get-login-password --region us-east-1 \
              | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com || true

            # Restart systemd (đã pull latest trong unit)
            sudo systemctl restart be

            # Đợi app UP
            for i in $(seq 1 20); do
              if curl -fsS http://localhost/actuator/health | grep -q '"status":"UP"'; then
                echo "Service is UP"; exit 0
              fi
              sleep 2
            done

            # Nếu chưa UP, in log và fail
            sudo journalctl -u be -n 200 --no-pager || true
            exit 1
